server:
  port: 8040

spring:
  application:
    name: user
  datasource:
    name: db_crouse
    url: jdbc:mysql://172.17.0.1:3306/db_crouse?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.southwind.entity
